version: "3.8"

services:
  backend:
    image: ghcr.io/namleeewatatek/wataai/backend:${BACKEND_TAG:-latest}
    pull_policy: always
    container_name: aiwata-backend
    restart: unless-stopped
    env_file:
      - backend/.env
    environment:
      NODE_ENV: production
    ports:
      - "8000:8000"
    networks:
      - wata-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 1G

  web:
    image: ghcr.io/namleeewatatek/wataai/web:${WEB_TAG:-latest}
    pull_policy: always
    container_name: aiwata-web
    restart: unless-stopped
    env_file:
      - web/.env
    environment:
      - NODE_ENV=production
      - INTERNAL_API_URL=http://backend:8000/api/v1
    ports:
      - "3001:3000"
    networks:
      - wata-network
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  wata-network:
    external: true
