'use client';

import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Library, LayoutGrid, List, Search as SearchIcon, RotateCcw } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/Button';
import { Pagination } from '@/components/shared/Pagination';
import { useAssets } from '@/lib/hooks/features/useAssets';
import { PageHeader } from '@/components/shared/PageHeader';
import { subDays } from 'date-fns';
import { cn } from '@/lib/utils';
import {
    Card,
    CardContent
} from "@/components/ui/Card";
import { Search } from '@/components/shared/Search';
import { ProductsGrid } from '@/components/features/products/ProductsGrid';
import { ProductsTable } from '@/components/features/products/ProductsTable';
import { CreationJobStatus, CreationJob } from '@/lib/types/creation-job';
import { Asset } from '@/lib/types/asset';
import { useMemo } from 'react';

export default function AssetsPage() {
    const [viewMode, setViewMode] = useState<'grid' | 'table'>('grid');
    const { t } = useTranslation();

    const {
        assets,
        total,
        hasNextPage,
        isLoading,
        isRefetching,
        page,
        pageSize,
        searchFilter,
        setPage,
        setPageSize,
        setSearchFilter,
        refresh,
        deleteAsset
    } = useAssets({
        page: 1,
        pageSize: 12,
    });

    const mappedJobs = useMemo(() => {
        return assets.map((asset: Asset) => ({
            id: asset.id,
            status: CreationJobStatus.COMPLETED,
            creationTool: {
                id: asset.metadata?.toolId,
                name: asset.metadata?.toolName || 'Asset'
            },
            outputData: asset.metadata || { result: asset.url },
            inputData: {},
            progress: 100,
            createdAt: asset.createdAt,
            updatedAt: asset.updatedAt,
        } as unknown as CreationJob));
    }, [assets]);

    const handleRefresh = () => {
        refresh();
    };

    const handleDelete = async (id: string) => {
        try {
            await deleteAsset(id);
            toast.success("Asset deleted");
        } catch (error) {
            toast.error("Failed to delete asset");
        }
    };

    return (
        <div className="page-container space-y-6">
            <PageHeader
                title={t('navigation.assets')}
                description="Browse all successful media assets generated by your AI tools."
                icon={Library}
                onRefresh={handleRefresh}
                refreshing={isLoading || isRefetching}
            />

            <Card className="overflow-hidden flex flex-col border-border/50 bg-card/30 backdrop-blur-sm">
                <div className="px-6 py-4 border-b bg-card/50 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
                    <div className="relative w-full sm:w-[350px]">
                        <Search
                            placeholder="Search assets..."
                            value={searchFilter}
                            onChange={(e: React.ChangeEvent<HTMLInputElement>) => setSearchFilter(e.target.value)}
                            onClear={() => setSearchFilter('')}
                        />
                    </div>

                    <div className="flex items-center gap-3">
                        <Button
                            variant="outline"
                            size="icon"
                            onClick={handleRefresh}
                            disabled={isLoading || isRefetching}
                            className="h-9 w-9"
                        >
                            <RotateCcw className={cn("h-4 w-4", (isLoading || isRefetching) && "animate-spin")} />
                        </Button>

                        <div className="border border-border/40 rounded-lg p-1 flex items-center gap-1 bg-muted/20">
                            <Button
                                variant="ghost"
                                size="icon"
                                className={cn(
                                    "h-8 w-8 rounded-md transition-all",
                                    viewMode === 'grid' ? "bg-background shadow-sm text-primary" : "text-muted-foreground"
                                )}
                                onClick={() => setViewMode('grid')}
                            >
                                <LayoutGrid className="w-4 h-4" />
                            </Button>
                            <Button
                                variant="ghost"
                                size="icon"
                                className={cn(
                                    "h-8 w-8 rounded-md transition-all",
                                    viewMode === 'table' ? "bg-background shadow-sm text-primary" : "text-muted-foreground"
                                )}
                                onClick={() => setViewMode('table')}
                            >
                                <List className="w-4 h-4" />
                            </Button>
                        </div>
                    </div>
                </div>

                <CardContent className="p-6 flex-1">
                    {viewMode === 'grid' ? (
                        <>
                            <ProductsGrid
                                jobs={mappedJobs}
                                isLoading={isLoading}
                                onDelete={handleDelete}
                                onRefresh={handleRefresh}
                            />
                            <div className="mt-6 border-t pt-6">
                                <Pagination
                                    pagination={{
                                        page,
                                        limit: pageSize,
                                        total: total,
                                        totalPages: Math.ceil(total / pageSize),
                                        hasNextPage
                                    }}
                                    onPageChange={setPage}
                                    onPageSizeChange={setPageSize}
                                    pageSizeOptions={[12, 24, 48]}
                                />
                            </div>
                        </>
                    ) : (
                        <ProductsTable
                            jobs={mappedJobs}
                            isLoading={isLoading}
                            onDelete={handleDelete}
                            onRefresh={handleRefresh}
                            pagination={{
                                page,
                                limit: pageSize,
                                total: total,
                                totalPages: Math.ceil(total / pageSize),
                                hasNextPage
                            }}
                            onPageChange={setPage}
                            onPageSizeChange={setPageSize}
                            pageSizeOptions={[12, 24, 48]}
                            searchFilter={searchFilter}
                            onSearchChange={setSearchFilter}
                        />
                    )}
                </CardContent>
            </Card>
        </div>
    );
}
